### ISSUE TITLE
  Bugfix - RepositoryBase 

### ISSUE THREAD

**Issue by titobundy** [Thavarajan/Mangoose-Typescript-With-Repository-Pattern#1]
Hi,

In line 3 of **RepositoryBase** class you have :

`import IHeroModel = require("./../../model/interfaces/HeroModel");`

This class should not have references to a specific model.

I am searching for a NestJS repository pattern implementation using moongose, do you think this project can be adapted for that ?

**Comment by Thavarajan** [comment]
Nope
